### ISSUE TITLE
Unable to get it to work with Rails/Webpacker

### ISSUE THREAD

**Issue by jesster2k10** [ben-rogerson/twin.macro#119]
Hey there, I've been using this library for sometime and it's been great. The setup has always been seamless and I've never ran into issues untill now.

I'm trying to setup the library in a sort of "non-typical" setting, being using Ruby on Rails and the [webpacker](https://github.com/rails/webpacker) gem.

So far, I've been getting random weird errors to do with the `babel-plugin-macros` and a console error.
Whenever I make a change, the following output is printed in the console:

```bash
WARNING in ./node_modules/babel-plugin-macros/dist/index.js 78:24-31
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:22)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1185:12

WARNING in ./node_modules/twin.macro/macro.js 67:61-80
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:22)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1185:12

WARNING in ./node_modules/import-fresh/index.js 32:32-49
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/dependencies/ContextDependency.js:40:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1454:24)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1258:10
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1253:28)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (/Users/jesseonolememen/Documents/pagg/pagg/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:44:22)
    at /Users/jesseonolememen/Documents/pagg/pagg/node_modules/webpack/lib/Compilation.js:1185:12
```

The 'twin.macro' import doesn't seem to work.
Given this example,

```tsx
import 'twin.macro'
import React from 'react'
import {render} from 'react-dom'

const Test = () => {
  return (
    <div tw="flex flex-col">
      <h1>Test Component</h1>
    </div>
  );
};

document.addEventListener('turbolinks:load', () => {
  render(<Test />, document.querySelector('.js-test-render')
})
```

The output I get is:

![Screenshot 2020-07-31 at 13 24 26](https://user-images.githubusercontent.com/6454286/89034578-296ba480-d331-11ea-95ca-1ff5e73cebbe.png)

So nothing is being compiled.
When I import the `tw` macro directly and use it like so:

`css={tw`flex flex-col}``

I get this error in the console:

![Screenshot 2020-07-31 at 13 25 15](https://user-images.githubusercontent.com/6454286/89034635-456f4600-d331-11ea-83c2-e72e6aab9a77.png)

Likewise, when I try to use 

`tw.div`flex flex-col``

I get a similar error:

![Screenshot 2020-07-31 at 13 25 53](https://user-images.githubusercontent.com/6454286/89034674-5cae3380-d331-11ea-9b9f-e1dbc69c395b.png)

It's worth nothing that when I add an incorrect, or missing, tailwind class no error is given.

**Comment by jesster2k10** [comment]
babel.config.js

```js
module.exports = function babelConfig(api) {
  const validEnv = ['development', 'test', 'production'];
  const currentEnv = api.env();
  const isDevelopmentEnv = api.env('development');
  const isProductionEnv = api.env('production');
  const isTestEnv = api.env('test');

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      `${
        'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: '
      }${JSON.stringify(currentEnv)}.`
    );
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current',
          },
          modules: 'commonjs',
        },
        '@babel/preset-react',
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol'],
        },
      ],
      [
        '@babel/preset-react',
        {
          development: isDevelopmentEnv || isTestEnv,
          useBuiltIns: true,
        },
      ],
      '@emotion/babel-preset-css-prop',
    ].filter(Boolean),
    plugins: [
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true,
        },
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true,
        },
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
          regenerator: true,
          corejs: false,
        },
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false,
        },
      ],
      isProductionEnv && [
        'babel-plugin-transform-react-remove-prop-types',
        {
          removeImport: true,
        },
      ],
      ['macros'],
      [
        '@emotion/babel-plugin-jsx-pragmatic',
        {
          module: '@emotion/core',
          export: 'jsx',
          import: '__cssprop',
        },
      ],
      ['@babel/plugin-transform-react-jsx', { pragma: '__cssprop' }],
    ].filter(Boolean),
  };
};
```

**Comment by jesster2k10** [comment]
Update: I've looked at #88 and I'm not sure if that applies in this case since I'm using Webpack & Babel

**Comment by ben-rogerson** [comment]
You can use Twin and TypeScript together.
It sort of looks like the css prop isn't enabled from your screenshot.

Could you upload a repo/codesandbox to demonstrate the issue?

PS: TypeScript starters are coming soon.

**Comment by jesster2k10** [comment]
> You can use Twin and TypeScript together.
> It sort of looks like the css prop isn't enabled from your screenshot.
> 
> Could you upload a repo/codesandbox to demonstrate the issue?
> 
> PS: TypeScript starters are coming soon.

Hey, so I actually figured it out. I was meaning to reply to this but I didn't get the chance. The issue was by setup was using `ts-loader` with wepback which doesn't play nicely with babel macros. The solution was simple, just to use `babel-loader` with `babel-preset-typescript` for my `.ts` files. 

Everything worked as expected although I still get the weird `_source="[Object object]"` in my DOM Tree.

**Comment by ben-rogerson** [comment]
Great you worked it out!
Yes, `ts-loader` doesn't play nice with babel-plugins, hopefully that changes in the future.

I'm seeing [some references within webpack to _source](https://github.com/webpack/webpack/blob/fdfaa2efa0b8ee2e6d0c55769696b3acb4047fb3/lib/NormalModule.js#L597), my guess - it seems to be something to do with the source map.

I'll close this now as I'm pretty sure that's not coming from Twin - feel free to reopen if you need.
