### ISSUE TITLE
Blitzjs + twin.macro "is not a function" error

### ISSUE THREAD

**Issue by jshnaidman** [ben-rogerson/twin.macro#584]
Hi. I'm using Blitzjs and when I try to write simple code like:

```
const Header = tw.header`
  flex justify-between items-center
  max-w-screen-xl mx-auto
`
```
I get:

```
warn  - ./node_modules/babel-plugin-macros/dist/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/import-fresh/index.js
Critical dependency: the request of a dependency is an expression

./node_modules/twin.macro/macro.js
Critical dependency: the request of a dependency is an expression
info  - ready on http://localhost:3000
TypeError: twin_macro__WEBPACK_IMPORTED_MODULE_2___default(...).header is not a function
    at eval (webpack-internal:///./app/core/components/treact_components/headers/light.js:37:74)
    at Object../app/core/components/treact_components/headers/light.js (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/pages/index.js:42:1)
    at __webpack_require__ (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/core/components/treact_pages/BlogIndex.tsx:15:112)
    at Object../app/core/components/treact_pages/BlogIndex.tsx (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/pages/index.js:92:1)
    at __webpack_require__ (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./app/pages/index.tsx:10:100)
    at Object../app/pages/index.tsx (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/pages/index.js:122:1)
    at __webpack_require__ (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/jshnaidm/projects/react_projects/jshnaidm_website/.next/server/pages/index.js:302:39)
```

However, if I write it like this:

```
const Header = <tw.header tw="flex justify-between items-center max-w-screen-xl mx-auto" />
```

It works. But if I want to write something like

```
tw(Input)`border-purple-500`
```

 then it doesn't work unfortunately and I'm not sure what kind of workaround I could do.

edit: I am using typescript with es6 with allowJs in my tsconfig.json set to true.

I'm not sure if this is enough information to reproduce the bug, so let me know if I can provide anything else. 
Thanks,
Jacob

**Comment by ben-rogerson** [comment]
Hey Jacob,
Hopefully the new [Blitz.js example](https://github.com/ben-rogerson/twin.examples/tree/master/blitz-emotion-typescript) can help you out with the setup, so be sure to check that out.
I think perhaps there's a plugin missing from your babel.config.js so compare it with [the babel.config.js from the example](https://github.com/ben-rogerson/twin.examples/blob/master/blitz-emotion-typescript/babel.config.js).

Another thing is that component cloning only works if the component is a styled component, eg:

```js
const Input = tw.div``
// or
const Input = styled.div()

tw(Input)`border-purple-500`
```

**Comment by jshnaidman** [comment]
Ahh I should have seen this example! Thank you! I appreciate it :)

**Comment by ben-rogerson** [comment]
Not your fault, it was pushed after you made this issue, hope it helps 👍
